# Generated by Django 3.2 on 2021-08-15 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_query_query_related'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='query_related',
            new_name='category_related',
        ),
    ]
