# Generated by Django 3.2 on 2021-08-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_historicalcategory_historicalquery_historicalreplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquery',
            name='operator_related',
            field=models.CharField(default=0, max_length=20, verbose_name='ادمین این تیکت'),
        ),
        migrations.AddField(
            model_name='query',
            name='operator_related',
            field=models.CharField(default=0, max_length=20, verbose_name='ادمین این تیکت'),
        ),
        migrations.AlterField(
            model_name='historicalquery',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('RESOLVED', 'Resolved'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('SUSPENDED', 'Suspended')], default='CREATED', max_length=20, verbose_name='وضعیت تیکت'),
        ),
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('RESOLVED', 'Resolved'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('SUSPENDED', 'Suspended')], default='CREATED', max_length=20, verbose_name='وضعیت تیکت'),
        ),
    ]
